config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root 'draft#index'

  get 'sign-in', to: 'authentication#new'
  post 'sign-in', to: 'authentication#create'
  get 'sign-out', to: 'authentication#destroy'

  resources :users, only: [:show] do
    resources :draft_picks, expect: [:index]
    resources :votes, only: [:create]
  end

  resources :rounds, only: [] do
    resources :matches, only: [:index, :new, :create]
  end

  get 'semifinals', to: 'draft#semifinals'
  get 'finals', to: 'draft#finals'
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password

  validates_presence_of :email
  validates_numericality_of :finals_order, greater_than_or_equal_to: 0
  validates_numericality_of :semifinals_order, greater_than_or_equal_to: 0

  has_many :draft_picks
  has_many :categories, through: :draft_picks
  has_many :votes

  scope :finalists, -> { where('finals_order > ?', 0).order(:finals_order) }
  scope :semifinalists, -> { where('semifinals_order > ?', 0).order(:semifinals_order) }

  def default_round
    self.draft_picks.empty? ? 1 : (self.draft_picks.size/2)+1
  end

  def first_pick_of_round(round_num)
    self.ordered_picks(round_num).first
  end

  def full_name
    "#{first_name} #{last_name}"
  end

  def has_not_voted_on_match?(match)
    self.votes.where(match_id: match).empty?
  end

  def is_finalist?
    finals_order > 0
  end

  def is_semifinalist?
    semifinals_order > 0
  end

  def match_participant?(match)
    [match.team1_id, match.team2_id].include?(self.id)
  end

  def opposing_teams
    User.where.not(id: self)
  end

  def ordered_picks(round_num)
    self.draft_picks.where(round_drafted: round_num).order(:created_at)
  end

  def second_pick_of_round(round_num)
    self.ordered_picks(round_num)[1]
  end

  def team_abbr
    self[:team_abbr].try(:upcase) || team_name.split(' ').map(&:first).reject {|char| char.upcase != char }.join('')
  end

  def team_abbr_and_name
    "#{team_abbr} (#{first_name})"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.includes(:draft_picks).find(params[:id])
    @categories = Category.all
  end
end

app/views/users/_category_picks.html.erb
<h3 class="text-center"><%= category.name%></h3>
<h5 class="text-center"><%= "Minimum: #{category.minimum}" %></h5>
<table class="table table-striped team-table">
  <colgroup>
    <col class="col-md-8"/>
    <col class="col-md-4"/>
  </colgroup>
  <thead>
    <tr>
      <th>Draft Pick</th>
      <th>Round Drafted</th>
    </tr>
  </thead>
  <tbody>
    <% user.draft_picks.where(category_id: category.id).order(:round_drafted, :created_at).each do |pick| %>
      <tr>
        <td><%= pick.name %></td>
        <td><%= pick.round_drafted%></td>
        <% if user == current_user %>
          <td>
            <%= link_to 'Edit',  '#', 'data-target' => "#editDraftPick_#{pick.id}", 'data-toggle' => 'modal', class: "btn btn-primary btn-sm"  %>
            <%= render 'draft_picks/edit', pick: pick %>
          </td>
          <td><%= link_to "Delete", user_draft_pick_path(user, pick), method: :delete, data: {confirm: "Are you sure?" }, class: "btn btn-warning btn-sm" %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>

</table>

app/views/users/show.html.erb
<div class="container">
  <div class="page-header">
    <h1><%= "#{@user.first_name} - #{@user.team_name} (#{@user.team_abbr})" %></h1>
  </div>
  <% @categories.each do |category| %>
    <%= render partial: 'category_picks', locals: {user: @user, category: category} %>
  <% end %>
</div>