config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root 'draft#index'

  get 'sign-in', to: 'authentication#new'
  post 'sign-in', to: 'authentication#create'
  get 'sign-out', to: 'authentication#destroy'

  resources :users, only: [:show] do
    resources :draft_picks, expect: [:index]
    resources :votes, only: [:create]
  end

  resources :rounds, only: [] do
    resources :matches, only: [:index, :new, :create]
  end

  get 'semifinals', to: 'draft#semifinals'
  get 'finals', to: 'draft#finals'
end

app/models/match.rb
class Match < ApplicationRecord
  has_many :votes

  def complete?
    User.all
      .reject { |user| user.match_participant?(self) }
      .none? { |user| user.has_not_voted_on_match?(self) }
  end

  def eligible_voters
    User.all.reject { |user| user.match_participant?(self) }
  end

  def team1
    User.includes(:draft_picks).find(team1_id)
  end

  def team2
    User.includes(:draft_picks).find(team2_id)
  end

  def votes_for_team(team)
    self.votes.where(vote_for_team_id: team.id).size
  end
end

app/controllers/matches_controller.rb
class MatchesController < ApplicationController
  def index
    @round = params[:round_id].to_i
    @matches = Match.where(round: @round)
  end

  def new
    @round = params[:round_id].to_i
    @match = Match.new(round: @round)
  end

  def create
    @round = params[:round_id].to_i
    @match = Match.new(match_params)
    @match.round = @round
    if @match.save
      redirect_to round_matches_path(@round), notice: "Match successfully added!"
    else
      render :new
    end
  end

  private

  def match_params
    params.require(:match).permit(:team1_id, :team2_id)
  end
end

app/views/matches/_team_match.html.erb
<tr>
  <% first_pick_of_round = team.first_pick_of_round(@round) %>
  <td><%= first_pick_of_round.try(:name).to_s %></td>
  <td><%= first_pick_of_round.try(:category).try(:name).to_s %></td>
</tr>
<tr>
  <% second_pick_of_round = team.second_pick_of_round(@round) %>
  <td><%= second_pick_of_round.try(:name).to_s %></td>
  <td><%= second_pick_of_round.try(:category).try(:name).to_s %></td>
</tr>
<% if current_user.has_not_voted_on_match?(match) && !current_user.match_participant?(match) %>
  <tr>
    <td colspan=2>
      <%= button_to "Vote for #{team.team_abbr}", user_votes_path(current_user, vote: {match_id: match.id, vote_for_team_id: team.id}), remote: true, class: "btn btn-danger vote_button_for_match_#{match.id}" %>
    </td>
  </tr>
<% elsif match.complete? %>
  <tr class="vote_totals">
    <td><%= "Total for #{team.team_abbr}:" %></td>
    <td><%= "#{match.votes_for_team(team)}" %></td>
  </tr>
<% end %>

app/views/matches/index.html.erb
<div class="container">
  <div class="page-header">
    <% if current_user.admin %>
      <div class="pull-right">
        <%= link_to "Make New Match", new_round_match_path(@round), class: "btn btn-danger btn-lg" %>
      </div>
    <% end %>
    <% if regular_play_rounds.include?(@round) %>
      <h1><%= "Round #{@round} Matches" %></h1>
    <% elsif semi_final_rounds.include?(@round) %>
      <h1><%= "Semi-Final Matches (Round #{@round})" %></h1>
    <% else %>
      <h1><%= "Final Match (Round #{@round})" %></h1>
    <% end %>
  </div>

  <% @matches.each do |match| %>
    <div class="team_match col-xs-6">
      <table class="table match_table">
        <tr>
          <th colspan=2><%= match.team1.team_abbr_and_name %></th>
        </tr>
        <%= render partial: "team_match", locals: {match: match, team: match.team1} %>
      </table>
    </div>
    <div class="team_match col-xs-6">
      <table class="table match_table">
        <tr>
          <th colspan=2><%= match.team2.team_abbr_and_name %></th>
        </tr>
        <%= render partial: "team_match", locals: {match: match, team: match.team2} %>
      </table>
    </div>
  <% end %>

  <% if current_user.admin %>
    <table class="table table-striped">
      <thead>
        <tr>
          <th>Match</th>
          <th>Has not voted</th>
        </tr>
      </thead>
      <tbody>
        <% @matches.each do |match| %>
          <tr>
            <td><%= "#{match.team1.team_abbr_and_name} vs #{match.team2.team_abbr_and_name}" %></td>
            <td><%= match.eligible_voters.select {|user| user.has_not_voted_on_match?(match) }.map(&:first_name).to_sentence %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  <% end %>


</div>

app/views/matches/new.html.erb
<div class="container">
  <div class="well">
    <h1 class="text-center"><%= "New Match for Round #{@round}"%></h1>
    <div class="form-inline">
      <%= form_for @match, url: round_matches_path(@round) do |f| %>
        <%= f.hidden_field :round_id, value: @round %>
        <%= render partial: 'shared/errors', locals: {object: @match} %>
        <div class="form-group">
          <%= f.label :team1_id, "Team 1" %>
          <%= f.collection_select(:team1_id, User.order(:first_name).all, :id, :team_abbr_and_name, {}, class: "form-control") %>
        </div>
        <div class="form-group">
          <%= f.label :team2_id, "Team 2" %>
          <%= f.collection_select(:team2_id, User.order(first_name: :desc).all, :id, :team_abbr_and_name, {}, class: "form-control") %>
        </div>
        <div class="form-group">
          <%= f.submit "Create Match", class: "btn btn-default" %>
        </div>
      <% end %>
    </div>
  </div>
</div>