config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root 'draft#index'

  get 'sign-in', to: 'authentication#new'
  post 'sign-in', to: 'authentication#create'
  get 'sign-out', to: 'authentication#destroy'

  resources :users, only: [:show] do
    resources :draft_picks, expect: [:index]
    resources :votes, only: [:create]
  end

  resources :rounds, only: [] do
    resources :matches, only: [:index, :new, :create]
  end

  get 'semifinals', to: 'draft#semifinals'
  get 'finals', to: 'draft#finals'
end

app/views/layouts/_nav.html.erb
<nav class="navbar navbar-default navbar-fixed-top navbar-inverse">
  <div class="container-fluid">
    <div class="navbar-header">
      <%= link_to "Draft Schedule", root_path, class: "navbar-brand" %>
    </div>
    <div class="collapse navbar-collapse">
      <ul class="nav navbar-nav">
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Teams<span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><%= link_to "My team", user_path(current_user) %></li>
            <li class="divider" role="separator"></li>
            <% current_user.opposing_teams.each do |team| %>
              <li><%= link_to team.team_abbr_and_name, user_path(team) %></li>
            <% end %>
          </ul>
        </li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Draft Matches<span class="caret"></span></a>
          <ul class="dropdown-menu">
            <% regular_play_rounds.each do |round_num| %>
              <!-- TODO: make link to matches -->
              <li><%= link_to "Round #{round_num}", round_matches_path(round_num) %></li>
            <% end %>
          </ul>
        </li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Semi-Finals<span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><%= link_to "Schedule", semifinals_path %></li>
            <% semi_final_rounds.each do |round_num| %>
              <!-- TODO: make link to matches -->
              <li><%= link_to "Matches (Round #{round_num})", round_matches_path(round_num) %></li>
            <% end %>
          </ul>
        </li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Finals<span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><%= link_to "Schedule", finals_path %></li>
            <% final_rounds.each do |round_num| %>
              <!-- TODO: make link to matches -->
              <li><%= link_to "Matches (Round #{round_num})", round_matches_path(round_num) %></li>
            <% end %>
          </ul>
        </li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <% if current_user %>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><%= current_user.full_name %><span class="caret"></span></a>
            <ul class="dropdown-menu">
              <li><%= link_to "My team", user_path(current_user) %></li>
            </ul>
          </li>
          <li><%= link_to "Sign Out", sign_out_path %></li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DL Draft 2017</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% if !@disable_nav %>
      <%= render 'layouts/nav' %>
    <% end %>
    <div class="container">
      <% if flash[:notice] %>
        <div class="alert alert-success">
          <%= notice %>
        </div>
      <% end %>
      <% if flash[:alert] %>
        <div class="alert alert-danger">
          <%= alert %>
        </div>
      <% end %>
    </div>
    <%= yield %>
  </body>
</html>